services:
    # Banners
    app.admin.banner:
        class: AppBundle\Admin\BannerAdmin
        arguments: [~, AppBundle\Entity\Banner, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "AdServer", label: "Banner" }

    # Categories
    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "AdServer", label: "Category" }

    # Brands
    app.admin.brands:
        class: AppBundle\Admin\BrandAdmin
        arguments: [~, AppBundle\Entity\Brand, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "AdServer", label: "Brand" }
