services:
    # Banners
    app.admin.banner:
        class: AppBundle\Admin\BannerAdmin
        arguments: [~, AppBundle\Entity\Banner, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "AdServer", label: "Banner" }

    # Campaigns
    app.admin.campaign:
        class: AppBundle\Admin\CampaignAdmin
        arguments: [~, AppBundle\Entity\Campaign, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "AdServer", label: "Campaign" }

    # Categories
    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "AdServer", label: "Category" }

    # Brands
    app.admin.brands:
        class: AppBundle\Admin\BrandAdmin
        arguments: [~, AppBundle\Entity\Brand, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "AdServer", label: "Brand" }

    # BannerLogs
    app.admin.banner_log:
        class: AppBundle\Admin\BannerLogAdmin
        arguments: [~, AppBundle\Entity\BannerLog, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Activities", label: "Logs" }

    # BannerClicks
    app.admin.banner_click:
        class: AppBundle\Admin\BannerClickAdmin
        arguments: [~, AppBundle\Entity\BannerClick, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Activities", label: "Clicks" }

    # BannerFeedbacks
    app.admin.banner_feedback:
        class: AppBundle\Admin\BannerFeedbackAdmin
        arguments: [~, AppBundle\Entity\BannerFeedback, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Activities", label: "Feedbacks" }            
